# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve using the piqp dense matrix interface
#'
#' @param P a symmetric positive definite matrix
#' @param c the objective cost
#' @param A the coefficient matrix of primal constraints
#' @param b the right hand side vector of the primal constraints
#' @param G the matrix of inequality constraints
#' @param h the right side vector of the matrix inequality constraints
#' @param x_lb the lower bounds for the solution
#' @param x_ub the upper bounds for the solution
#' @param rs a list of control settings
#' @return named list
#'   - `x` (primal solution)
#'   - `y` (dual solution of equality constraints)
#'   - `z` (dual solution of inequality constraints)
#'   - `z_lb` (dual solution of lower bound box constraints)
#'   - `z_ub` (dual solution of upper bound box constraints)
#'   - `obj` (primal objective value)
#'   - `run_time` (total runtime, if so specified in settings)
piqp_dense_solve <- function(P, c, A, b, G, h, x_lb, x_ub, rs) {
    .Call('_piqp_piqp_dense_solve', PACKAGE = 'piqp', P, c, A, b, G, h, x_lb, x_ub, rs)
}

#' Solve using the piqp sparse matrix interface
#'
#' @param P a symmetric positive definite matrix
#' @param c the objective cost
#' @param A the coefficient matrix of primal constraints
#' @param b the right hand side vector of the primal constraints
#' @param G the matrix of inequality constraints
#' @param h the right side vector of the matrix inequality constraints
#' @param x_lb the lower bounds for the solution
#' @param x_ub the upper bounds for the solution
#' @param rs a list of control settings
#' @return named list
#'   - `x` (primal solution)
#'   - `y` (dual solution of equality constraints)
#'   - `z` (dual solution of inequality constraints)
#'   - `z_lb` (dual solution of lower bound box constraints)
#'   - `z_ub` (dual solution of upper bound box constraints)
#'   - `obj` (primal objective value)
#'   - `run_time` (total runtime, if so specified in settings)
piqp_sparse_solve <- function(P, c, A, b, G, h, x_lb, x_ub, rs) {
    .Call('_piqp_piqp_sparse_solve', PACKAGE = 'piqp', P, c, A, b, G, h, x_lb, x_ub, rs)
}

